# Key = language code, value = text
declare -A texts
texts["en_ping_success"]="Internet connection established."
texts["ru_ping_success"]="Интернет соединение установлено."
texts["en_ping_fail"]="No connection to the server! Please connect to the internet and run the script again."
texts["ru_ping_fail"]="Отсутствует соединение с сервером! Пожалуйста, подключитесь к интернету и запустите скрипт снова."
texts["en_nar_cel"]="SDWEAK integrity violated, files corrupted or deleted! Reinstall SDWEAK!"
texts["ru_nar_cel"]="Нарушена целостность SDWEAK, файлы повреждены или удалены! Переустановите SDWEAK!"
texts["en_copable"]="SDWEAK is compatible with Steam Deck only!"
texts["ru_copable"]="SDWEAK совместим только со Steam Deck!"
texts["en_old_steamos"]="SDWEAK is only compatible with SteamOS 3.7 and higher! Please update your system!"
texts["ru_old_steamos"]="SDWEAK совместим только с SteamOS 3.7 и выше! Пожалуйста обновите систему!"
texts["en_optimization_start"]="SDWEAK installation begins..."
texts["ru_optimization_start"]="Начинается установка SDWEAK..."
texts["en_error_sv"]="A serious error has occurred! The system is corrupted, SDWEAK cannot be installed, call for help! TG: @biddbb"
texts["ru_error_sv"]="Произошла серьезная ошибка! Система повреждена, установка SDWEAK невозможна, обратитесь за помощью! TG: @biddbb"
texts["en_skip"]="Skipping..."
texts["ru_skip"]="Пропуск..."
texts["en_invalid_input"]="Invalid input. Please enter 'y' or 'n'."
texts["ru_invalid_input"]="Неправильный ввод. Пожалуйста, введите 'y' или 'n'."

texts["en_yet_mglru"]="MGLRU successfully activated."
texts["ru_yet_mglru"]="MGLRU успешно активирован."
texts["en_yet_ov"]="Input controller overclocking successfully activated."
texts["ru_yet_ov"]="Разгон контроллера ввода успешно активирован."
texts["en_yet_un"]="Unnecessary services have been successfully disabled."
texts["ru_yet_un"]="Ненужные службы успешно отключены."
texts["en_tweaks_install"]="Starting tweaks installation..."
texts["ru_tweaks_install"]="Начинается установка твиков..."
texts["en_daem_anan"]="Ananicy-cpp successfully installed."
texts["ru_daem_anan"]="Ananicy-cpp успешно установлен."
texts["en_sysctl_en"]="Optimized sysctl settings are successfully installed."
texts["ru_sysctl_en"]="Оптимизированные настройки sysctl успешно установлены."
texts["en_thp_shrink"]="Optimal THP settings have been successfully set."
texts["ru_thp_shrink"]="Оптимальные настройки THP успешно установлены."
texts["en_zram_optim"]="Optimal ZRAM settings have been successfully set."
texts["ru_zram_optim"]="Оптимальные настройки ZRAM успешно установлены."

texts["en_fix_install"]="Starting microstutters fix installation..."
texts["ru_fix_install"]="Начинается установка исправления микрозаиканий..."
texts["en_fix_success"]="Microstutters fix successfully installed."
texts["ru_fix_success"]="Исправление микрозаиканий успешно установлено."
texts["en_fix_prompt"]="Install microstutters fix?"
texts["ru_fix_prompt"]="Установить исправление микрозаиканий?"

texts["en_hz_install"]="Starting Overclocking to 70Hz installation..."
texts["ru_hz_install"]="Начинается установка разгона дисплея до 70Hz..."
texts["en_hz_success"]="Overclocking to 70Hz successfully installed."
texts["ru_hz_success"]="Разгон до 70Hz успешно установлен."
texts["en_hz_prompt"]="Overclock the display to 70Hz?"
texts["ru_hz_prompt"]="Разогнать дисплей до 70Hz?"

texts["en_batt_install"]="Starting to prioritize power efficiency..."
texts["ru_batt_install"]="Начинается установка приоритета энергоэффективности..."
texts["en_batt_success"]="Power efficiency prioritization successfully installed."
texts["ru_batt_success"]="Приоритет энергоэффективности успешно установлен."
texts["en_batt_prompt"]="Prioritize power efficiency? (BETA)"
texts["ru_batt_prompt"]="Установить приоритет энергоэффективности? (БЕТА)"

texts["en_kernel_install"]="Starting kernel installation..."
texts["ru_kernel_install"]="Начинается установка ядра..."
texts["en_kernel_success"]="Kernel successfully installed."
texts["ru_kernel_success"]="Ядро успешно установлено."
texts["en_kernel_prompt"]="Install optimized kernel?"
texts["ru_kernel_prompt"]="Установить оптимизированное ядро?"

texts["en_gpu_install"]="Starting GPU optimization..."
texts["ru_gpu_install"]="Начинается оптимизация GPU..."
texts["en_gpu_success"]="GPU optimizations applied successfully."
texts["ru_gpu_success"]="Оптимизации GPU успешно применены."
texts["en_gpu_prompt"]="Enable GPU optimizations? (BETA)"
texts["ru_gpu_prompt"]="Применить оптимизации GPU? (БЕТА)"

texts["en_sdweak_success"]="The installation of SDWEAK has been successfully completed! If you enjoy SDWEAK, you can also support the project's further development with a donation via the link in the GitHub repository. Thank you for using it!"
texts["ru_sdweak_success"]="Установка SDWEAK успешно завершена! Если вам понравится SDWEAK, вы также можете поддержать донатом дальнейшее развитие проекта по ссылке в репозитории на GITHUB. Спасибо за использование!"

texts["en_se"]="Installation completed in"
texts["ru_se"]="Установка завершена за"
texts["en_sec"]="seconds."
texts["ru_sec"]="секунды."

texts["en_reboot_prompt"]="Reboot to apply changes?"
texts["ru_reboot_prompt"]="Перезагрузить для применения изменений?"
texts["en_reboot_required"]="Reboot is required."
texts["ru_reboot_required"]="Обязательно перезагрузите."
